{% set name = "torchinfo" %}
{% set version = "1.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 24cf949cc65d3926638e845e0aa949feb65f3025c58a8b8e084969bd42e30c0b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pytorch >=1.6

test:
  imports:
    - torchinfo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tyleryep/torchinfo
  summary: Model summary in PyTorch, based off of the original torchsummary.
  license: MIT
  license_file: LICENSE
  doc_url: https://github.com/TylerYep/torchinfo#documentation

extra:
  recipe-maintainers:
    - TylerYep
    - sarthakpati
